services:
  server:
    build: ../task5/
    container_name: server

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  task6:
    name: task6
